services:
  # PHP-FPM service running WordPress.
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORDPRESS_FPM_VERSION: ${WORDPRESS_FPM_VERSION:-6.8-fpm-alpine}
    container_name: wordpress_php_fpm_${COOLIFY_CONTAINER_NAME:-default}
    restart: unless-stopped
    environment:
      # Mandatory WordPress Database Connection (Set in Coolify).
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD} # Mark as secret.
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      # Mandatory WordPress Security Keys & Salts (Generate & Set in Coolify as secrets).
      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}
      # Optional WordPress Configuration (Set in Coolify if needed).
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0} # 1 for debug, 0 for production.
      # Default SITE_URL/HOME to COOLIFY_URL if available, otherwise empty.
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL:-${COOLIFY_URL}}
      WORDPRESS_HOME: ${WORDPRESS_HOME:-${COOLIFY_URL}}
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - coolify
    healthcheck:
      test: ["CMD-SHELL", "php -f /var/www/html/wp-includes/version.php || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Nginx web server service.
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION:-1.27-alpine}
    container_name: wordpress_nginx_${COOLIFY_CONTAINER_NAME:-default}
    restart: unless-stopped
    volumes:
      - wordpress_files:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  wordpress_files:
  # nginx_logs:

networks:
  coolify:
    external: true
